services:
  tomcatwebsever:
        build: .
        ports:
            - "8080:8080"
        container_name: tomcatwebsever 
        volumes:
            - ./html:/opt/apache-tomcat-9.0.89/webapps
        network_mode: "host" 
        #restsrt: always
        
